CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE aluno (
    id_aluno integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(50) NOT NULL,
    data_de_nascimento timestamp without time zone NOT NULL,
    telefone character varying(11) NOT NULL,
    cpf character varying(11) NOT NULL,
    rg character varying(9) NOT NULL,
    endereco character varying(200) NOT NULL,
    nome_do_pai character varying(50) NOT NULL,
    nome_da_mae character varying(50) NOT NULL,
    bolsista boolean NOT NULL,
    data_de_inicio timestamp without time zone,
    motivo_de_saida character varying(100) NOT NULL,
    possui_instrumento_proprio boolean NOT NULL,
    tamanho_da_vestimenta character varying(50) NOT NULL,
    CONSTRAINT "PK_aluno" PRIMARY KEY (id_aluno)
);

CREATE TABLE funcionario (
    id_funcionario integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(50) NOT NULL,
    senha character varying(255) NOT NULL,
    CONSTRAINT "PK_funcionario" PRIMARY KEY (id_funcionario)
);

CREATE TABLE professor (
    id_professor integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(50) NOT NULL,
    senha character varying(255) NOT NULL,
    CONSTRAINT "PK_professor" PRIMARY KEY (id_professor)
);

CREATE TABLE banda (
    id_banda integer GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    id_professor integer NOT NULL,
    banda_pai_id integer,
    CONSTRAINT "PK_banda" PRIMARY KEY (id_banda),
    CONSTRAINT "FK_banda_banda_banda_pai_id" FOREIGN KEY (banda_pai_id) REFERENCES banda (id_banda),
    CONSTRAINT "FK_banda_professor_id_professor" FOREIGN KEY (id_professor) REFERENCES professor (id_professor) ON DELETE CASCADE
);

CREATE TABLE nota (
    id_nota integer GENERATED BY DEFAULT AS IDENTITY,
    valor_nota numeric(10,2) NOT NULL,
    mes timestamp without time zone NOT NULL,
    musica text NOT NULL,
    descricao text NOT NULL,
    id_aluno integer NOT NULL,
    id_professor integer NOT NULL,
    CONSTRAINT "PK_nota" PRIMARY KEY (id_nota),
    CONSTRAINT "FK_nota_aluno_id_aluno" FOREIGN KEY (id_aluno) REFERENCES aluno (id_aluno) ON DELETE CASCADE,
    CONSTRAINT "FK_nota_professor_id_professor" FOREIGN KEY (id_professor) REFERENCES professor (id_professor) ON DELETE CASCADE
);

CREATE TABLE banda_aluno (
    id_aluno integer NOT NULL,
    id_banda integer NOT NULL,
    CONSTRAINT "PK_banda_aluno" PRIMARY KEY (id_aluno, id_banda),
    CONSTRAINT "FK_banda_aluno_aluno_id_aluno" FOREIGN KEY (id_aluno) REFERENCES aluno (id_aluno) ON DELETE CASCADE,
    CONSTRAINT "FK_banda_aluno_banda_id_banda" FOREIGN KEY (id_banda) REFERENCES banda (id_banda) ON DELETE CASCADE
);

CREATE TABLE presenca (
    id_presenca integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(50) NOT NULL,
    data timestamp without time zone NOT NULL,
    presenca boolean NOT NULL,
    id_banda integer,
    id_aluno integer NOT NULL,
    id_professor integer NOT NULL,
    CONSTRAINT "PK_presenca" PRIMARY KEY (id_presenca),
    CONSTRAINT "FK_presenca_aluno_id_aluno" FOREIGN KEY (id_aluno) REFERENCES aluno (id_aluno) ON DELETE CASCADE,
    CONSTRAINT "FK_presenca_banda_id_banda" FOREIGN KEY (id_banda) REFERENCES banda (id_banda),
    CONSTRAINT "FK_presenca_professor_id_professor" FOREIGN KEY (id_professor) REFERENCES professor (id_professor) ON DELETE CASCADE
);

CREATE INDEX "IX_banda_banda_pai_id" ON banda (banda_pai_id);

CREATE INDEX "IX_banda_id_professor" ON banda (id_professor);

CREATE INDEX "IX_banda_aluno_id_banda" ON banda_aluno (id_banda);

CREATE INDEX "IX_nota_id_aluno" ON nota (id_aluno);

CREATE INDEX "IX_nota_id_professor" ON nota (id_professor);

CREATE INDEX "IX_presenca_id_aluno" ON presenca (id_aluno);

CREATE INDEX "IX_presenca_id_banda" ON presenca (id_banda);

CREATE INDEX "IX_presenca_id_professor" ON presenca (id_professor);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260530151619_CriacaoInicial', '10.0.8');

COMMIT;

