// <auto-generated />
using System;
using ComucAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComucAPI.Migrations
{
    [DbContext(typeof(ComucDbContext))]
    partial class ComucDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComucAPI.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_aluno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAluno"));

                    b.Property<bool>("Bolsista")
                        .HasColumnType("boolean")
                        .HasColumnName("bolsista");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_de_inicio");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_de_nascimento");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endereco");

                    b.Property<string>("MotivoSaida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("motivo_de_saida");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome_da_mae");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome_do_pai");

                    b.Property<bool>("PossuiInstrumento")
                        .HasColumnType("boolean")
                        .HasColumnName("possui_instrumento_proprio");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("rg");

                    b.Property<string>("TamanhoVestimenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tamanho_da_vestimenta");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.HasKey("IdAluno");

                    b.ToTable("aluno");
                });

            modelBuilder.Entity("ComucAPI.Models.Banda", b =>
                {
                    b.Property<int>("IdBanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_banda");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBanda"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("banda_pai_id")
                        .HasColumnType("integer")
                        .HasColumnName("banda_pai_id");

                    b.Property<int>("id_professor")
                        .HasColumnType("integer")
                        .HasColumnName("id_professor");

                    b.HasKey("IdBanda");

                    b.HasIndex("banda_pai_id");

                    b.HasIndex("id_professor");

                    b.ToTable("banda");
                });

            modelBuilder.Entity("ComucAPI.Models.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_funcionario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFuncionario"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha");

                    b.HasKey("IdFuncionario");

                    b.ToTable("funcionario");
                });

            modelBuilder.Entity("ComucAPI.Models.Nota", b =>
                {
                    b.Property<int>("IdNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_nota");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNota"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTime>("Mes")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mes");

                    b.Property<string>("Musica")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("musica");

                    b.Property<decimal>("ValorNota")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_nota");

                    b.Property<int>("id_aluno")
                        .HasColumnType("integer");

                    b.Property<int>("id_professor")
                        .HasColumnType("integer");

                    b.HasKey("IdNota");

                    b.HasIndex("id_aluno");

                    b.HasIndex("id_professor");

                    b.ToTable("nota");
                });

            modelBuilder.Entity("ComucAPI.Models.Presenca", b =>
                {
                    b.Property<int>("IdPresenca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_presenca");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPresenca"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data");

                    b.Property<int>("IdAluno")
                        .HasColumnType("integer")
                        .HasColumnName("id_aluno");

                    b.Property<int?>("IdBanda")
                        .HasColumnType("integer")
                        .HasColumnName("id_banda");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("integer")
                        .HasColumnName("id_professor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean")
                        .HasColumnName("presenca");

                    b.HasKey("IdPresenca");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdBanda");

                    b.HasIndex("IdProfessor");

                    b.ToTable("presenca");
                });

            modelBuilder.Entity("ComucAPI.Models.Professor", b =>
                {
                    b.Property<int>("IdProfessor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_professor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProfessor"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha");

                    b.HasKey("IdProfessor");

                    b.ToTable("professor");
                });

            modelBuilder.Entity("banda_aluno", b =>
                {
                    b.Property<int>("id_aluno")
                        .HasColumnType("integer");

                    b.Property<int>("id_banda")
                        .HasColumnType("integer");

                    b.HasKey("id_aluno", "id_banda");

                    b.HasIndex("id_banda");

                    b.ToTable("banda_aluno");
                });

            modelBuilder.Entity("ComucAPI.Models.Banda", b =>
                {
                    b.HasOne("ComucAPI.Models.Banda", "BandaPai")
                        .WithMany("SubTurmas")
                        .HasForeignKey("banda_pai_id");

                    b.HasOne("ComucAPI.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("id_professor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BandaPai");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ComucAPI.Models.Nota", b =>
                {
                    b.HasOne("ComucAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("id_aluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComucAPI.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("id_professor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ComucAPI.Models.Presenca", b =>
                {
                    b.HasOne("ComucAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComucAPI.Models.Banda", "Banda")
                        .WithMany()
                        .HasForeignKey("IdBanda");

                    b.HasOne("ComucAPI.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Banda");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("banda_aluno", b =>
                {
                    b.HasOne("ComucAPI.Models.Aluno", null)
                        .WithMany()
                        .HasForeignKey("id_aluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComucAPI.Models.Banda", null)
                        .WithMany()
                        .HasForeignKey("id_banda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComucAPI.Models.Banda", b =>
                {
                    b.Navigation("SubTurmas");
                });
#pragma warning restore 612, 618
        }
    }
}
